config/routes.rb
Rails.application.routes.draw do
  resources :certifications, only: [:show, :index]
  resources :projects, only: [:show, :index]
  resources :skills, only: [:show, :index]
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/certification.rb
class Certification < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :overview, presence: true
  validates :technologies, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :skills
  has_many :certifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :set_certification, only: [:show]

  # GET /certifications
  def index
    @certifications = Certification.all
  end

  # GET /certifications/1
  def show; end

  private

  def set_certification
    @certification = Certification.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @projects = Project.all
  end

  def show; end

  private

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show]
  def index
    @skills = Skill.all
  end

  def show; end

  private

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:name, :category)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @projects = Project.all
    @skills = Skill.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/certifications/index.html.erb
<h1>Certifications</h1>

app/views/certifications/show.html.erb
<h1>Certifications</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Add Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Add Font Awesome JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=Nunito:wght@400;500;600&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

app/views/projects/show.html.erb
<header>
    <h1><a class="titleHeader" href="/">Federica Ulzurrun</a></h1>
    <nav class="menuDesk">
        <a class="navLink desk" href="/#projects">Portfolio</a>
        <a class="navLink desk" href="/#about-me">About Me</a>
        <a class="navLink desk" href="/#contact-me">Contact Me</a>
    </nav>
    <button id="menu-toggle"><i class="fa-solid fa-bars"></i></button>
</header>
<div id="mobileMenu">
    <ul>
        <li><a class="navLink" href="/#projects">Portfolio</a></li>
        <li><a class="navLink" href="/#about-me">About Me</a></li>
        <li><a class="navLink" href="/#contact-me">Contact Me</a></li>
    </ul>
</div>
<section class="welcomeMain especific">
  <div class="project-especific">
    <div class="project-imageCont">
      <% if @project.url_photo.present? %>
        <%= image_tag @project.url_photo, alt: 'Project Photo', class: 'project-image' %>
      <% end %>
    </div>
    <div class="project-especificDetails">
      <h1 class="project-title"><%= @project.title %></h1>
      <p class="project-info"><strong>Overview:</strong> <%= @project.overview %></p>
      <p class="project-info"><strong>Start Date:</strong> <%= @project.start_date %></p>
      <p class="project-info"><strong>End Date:</strong> <%= @project.end_date %></p>
      <p class="project-info">
        <strong>Github URL:</strong>
        <a href="<%= @project.github_url %>" target="_blank" class="projectTags">Check it out here!</a>
      </p>
      <p class="project-info">
        <strong>Demo URL:</strong>
        <a href="<%= @project.demo_url %>" target="_blank" class="projectTags">Check it out here!</a>
      </p>
      <p class="project-info"><strong>Technologies:</strong> <%= @project.technologies %></p>
      <p class="project-info"><strong>Details:</strong></p>
      <p class="project-info"><%= @project.details %></p>
    </div>
    <%= link_to 'Back', root_path, class: 'btn btnForm' %>
  </div>
</section>

<footer>
    <div class="socials">
      <a href="mailto:fzulzurrun@gmail.com"><i class="fa-solid fa-envelope"></i></a>
      <a href="https://www.linkedin.com/in/federicaulzurrun/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
      <a href="https://github.com/federicaulzurrun" target="_blank"><i class="fa-brands fa-github"></i></a>        
    </div>
    <p class="copyR">&copy; 2023 Federica Ulzurrun</p>
</footer>

app/views/skills/index.html.erb
<h1>Skills</h1>

app/views/skills/show.html.erb
<h1>Skills</h1>

app/views/welcome/index.html.erb
<header>
    <h1><a class="titleHeader" href="#welcomeMain">Federica Ulzurrun</a></h1>
    <nav class="menuDesk">
        <a class="navLink desk" href="#projects">Portfolio</a>
        <a class="navLink desk" href="#about-me">About Me</a>
        <a class="navLink desk" href="#contact-me">Contact Me</a>
    </nav>
    <button id="menu-toggle"><i class="fa-solid fa-bars"></i></button>
</header>
<div id="mobileMenu">
    <ul>
        <li><a class="navLink" href="#projects">Portfolio</a></li>
        <li><a class="navLink" href="#about-me">About Me</a></li>
        <li><a class="navLink" href="#contact-me">Contact Me</a></li>
    </ul>
</div>
<main class="welcomeMain" id="welcomeMain">
    <div class="presentation">
        <h2 class="titleName">Federica Ulzurrun </h2>
        <h3>Welcome to my coding world</h3>
        <p>
            Over the past two years, I have had the opportunity to work on several incredible projects that have allowed me to grow and find my place in this competitive industry. I hope you enjoy viewing my projects as much as I enjoyed working on them.
        </p>
    </div>
    <div id="projects">
        <h2>Projects</h2>
        <div class="projects-cont">
            <% if @projects.present? %>
                <% @projects.each do |project| %>
                <%= link_to project_path(project) do %>
                    <div class="project-card">
                        <% if project.url_photo.present? %>
                            <div class="project-imageCont">
                                <%= image_tag project.url_photo, alt: project.title, class: "project-image" %>
                            </div>
                        <% end %>
                        <div class="project-info">
                            <h4 class="project-title"><%= project.title %></h4>
                            <p class="project-overview"><%= project.overview %></p>
                            <div class="project-btn">
                                <% if project.github_url.present? %>
                                    <%= link_to "Repository", project.github_url, target: "_blank", class: "btn btn-primary" %>
                                <% end %>
                                <% if project.demo_url.present? %>
                                    <%= link_to "Live demo", project.demo_url, target: "_blank", class: "btn btn-secondary" %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
                <% end %>
            <% else %>
                <p>No projects found.</p>
            <% end %>
        </div>
    </div>

    <div id="about-me">
        <div class="border-about">
            <h2>About Me</h2>
            <p class="description-about">
                I am Federica, a highly dedicated Software Developer with a well-rounded background in customer service and digital marketing. My journey in the world of software development has been shaped by a year-long intensive program at Microverse, where I've cultivated expertise in a wide spectrum of technologies including JavaScript, React, Redux, Ruby and Ruby on Rails.
            </p>
        </div>
    </div>

    <div class="skills-container">
        <h2>Skills</h2>
        <div class="skills-wrapper">
            <% categories = @skills.pluck(:category).uniq %>
            <% categories.each do |category| %>
            <div class="skill-category">
                <h4><%= category %></h4>
                <% @skills.where(category: category).each do |skill| %>
                <p><%= skill.name %></p>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>

    <div id="contact-me">
        <h2>Contact Information</h2>
        <h5>
            Feel free to contact me!
        </h5>
        <form action="https://formspree.io/f/mgebklpe" method="POST" class="contact-form" onsubmit="clearForm()">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        
        <label for="message">Message:</label>
        <textarea id="message" name="message" rows="4" required></textarea>
        
        <button class="btn btnForm" type="submit">Send</button>
    </form>

    </div>
</main>

<footer>
    <div class="socials">
        <a href="mailto:fzulzurrun@gmail.com"><i class="fa-solid fa-envelope"></i></a>
        <a href="https://www.linkedin.com/in/federicaulzurrun/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
        <a href="https://github.com/federicaulzurrun" target="_blank"><i class="fa-brands fa-github"></i></a>        
    </div>
    <p class="copyR">&copy; 2023 Federica Ulzurrun</p>
</footer>